### ISSUE TITLE
Unable to Instantiate Windows on Screen Initialization

### ISSUE THREAD

**Issue by bianc104** [peterhinch/micropython-touch#11]
I've been looking to instantiate a window alongside a new screen as the aim is to have part of the screen stay consistent (the screen) while the other portion is flexible/interchangeable (the window). I've attempted multiple different methods to accomplish this, culminating in extracting the Screen.change functions as demonstrated in screen_change.py and screen_replace.py and placing those at the end of the initialization of my screen class, but it seems to just perform that Screen.change call without making any visible difference to the actual screen. I've also tried to instantiate the window akin to one of the included widgets (by simply calling it directly on its own) with similar results.

Tying the instantiation of the window to a button press like in the aforementioned examples allows it to instantiate, however that does not help me as my use case requires the window present from the initialization of the screen.

Any help would be greatly appreciated!

**Comment by peterhinch** [comment]
This is not something I've tried. I take it that instantiating the `Window` from a button press does what you need, except for the requirement for a button press. If this is the case, one thing to try is to create an `after_open` method for your base screen (see the `primitives.py` demo and docs). Have this instantiate the `Window`.

Failing this, an option would be to have `after_open` launch an `asyncio` task:
```py
def after_open(self):
    asyncio.create_task(self.launch())

async def launch(self):
    await asyncio.sleep_ms(500)  # an arbitrary delay
    Screen.change(whatever)
```
This is rather clutching at straws, though. It's emulating the button press, but I don't think a delay should be required.

**Comment by bianc104** [comment]
Thank you for your response! Your first suggestion of moving to the after_open method appears to have worked!
I am running into another related issue, however, which may just be a limitation of the library/hardware; perhaps you can clarify it for me:

I'm trying to rewrite text in the lower screen based on inputs from the upper window (sort of like the "Result from dialog box." in screens.py, but the window in this case doesn't close after entry). It appears that I am able to successfully acquire the initial text and then update it using .value(), however the text on the bottom screen does not visually update until the window is closed. I assume this is because the bottom screen is graphically suspended, likely to conserve RAM, but I'm wondering if there is any way to force a refresh of the bottom screen while the window is still open?

Thanks again for your help!

**Comment by peterhinch** [comment]
I'm afraid not. The GUI has a "current screen" which has the focus - only widgets on that screen are refreshed. A prior screen exists merely as a display image; it won't be refreshed until it becomes current. That is rather fundamental to the design and I don't think it could easily be changed.

**Comment by bianc104** [comment]
Alright, that makes sense, thanks for your clarification!
