### ISSUE TITLE
Issue with inadequate documentation

### ISSUE THREAD

**Issue by Akash47007** [peterhinch/micropython-touch#14]
I am having issues running this library with a common setup containing a raspberry pi pico w and 240*320 lcd TFT display.
Please write an example code that tests all the functionality of the widgets or simply just gets a few buttons and labels working.
I am getting a blank screen and memory allocation issue for a long time of debugging and decided to give up.
Please help.

**Comment by peterhinch** [comment]
Please check out the example scripts in `gui/demos/`. These can be run with (for example):
```bash
$ mpremote mount . exec "import gui.demos.simple"
```
There are scripts to test every widget.

**Comment by peterhinch** [comment]
These scripts are listed [here in the main README](https://github.com/peterhinch/micropython-touch/blob/master/README.md#17-files). If you still think there are omissions in the docs, please detail these in a new issue.

**Comment by Akash47007** [comment]
I mean I need a working example code that I can upload and test and learn from it. **I cannot make it working with the existing documentation.**

**Comment by peterhinch** [comment]
If you work through [the setup doc](https://github.com/peterhinch/micropython-touch/blob/master/SETUP.md) then all the scripts listed will work. They are designed to be studied and to help in writing applications, starting with `simple.py`. I'm not sure what else you want me to provide.
