### ISSUE TITLE
Demo: Calendar >>>  ImportError: can't perform relative import

### ISSUE THREAD

**Issue by zoland** [peterhinch/micropython-touch#18]
17:  from .date import DateCal

>>> %Run -c $EDITOR_CONTENT

MPY: soft reboot
Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
ImportError: can't perform relative import
>>>

**Comment by peterhinch** [comment]
I can't replicate this.

You need to run the demos from the touch GUI root, so you run the demo with
```py
>>> import gui.demos.calendar
```

**Comment by zoland** [comment]
You're right, everything worked out, thank you
